version: '3.1'

services:
  mongo:
    image: mongo:3.6
    container_name: koohoo-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: koohoo
      MONGO_INITDB_ROOT_USERNAME: koohoo
      MONGO_INITDB_ROOT_PASSWORD: telenor123
    volumes: 
      - "./data:/data/db"
    ports: 
      - "27017:27017"